providers = ["bun"]

[phases.build]
dependsOn = ["install"]

[phases.install]
cmds = [
  "apt-get update",
  "apt-get install -y wget gnupg ca-certificates procps libxss1 libgconf-2-4 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libcairo-gobject2 libgtk-3-0 libgdk-pixbuf2.0-0 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libcairo-gobject2 libdrm2 libxkbcommon0 libatspi2.0-0",
  "bun install"
]

[phases.start]
cmd = "bun index.ts"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
PUPPETEER_CACHE_DIR = "/app/.cache/puppeteer" 