providers = ["node"]

[phases.build]
cmds = ["npx puppeteer browsers install chrome"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
PUPPETEER_CACHE_DIR = "/tmp/.chrome" 