providers = ["node"]

[phases.setup]
aptPkgs = ["chromium"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
CHROMIUM_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true" 