providers = ["node"]

[phases.setup]
aptPkgs = [
    "chromium-browser", 
    "chromium-browser-l10n",
    "fonts-liberation",
    "libnss3",
    "libxss1",
    "libgconf-2-4",
    "libxtst6",
    "libxrandr2",
    "libasound2",
    "libpangocairo-1.0-0",
    "libatk1.0-0",
    "libcairo-gobject2",
    "libgtk-3-0",
    "libgdk-pixbuf2.0-0"
]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser" 