providers = ["node"]

[phases.setup]
aptPkgs = ["chromium", "chromium-sandbox"]

[phases.build]
dependsOn = ["setup"]

[phases.install]
dependsOn = ["setup"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium" 